name: Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY_WEB: ${{ secrets.API_KEY_WEB }}
      MAPS_API_KEY_WEB: ${{ secrets.MAPS_API_KEY_WEB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1' # Replace with your Flutter version

      - name: Install dependencies
        run: flutter pub get
      
      - name: Configure main.dart to Web Configuration
        run: dart run update_main_config.dart
      
      - name: Set Maps Api Key in index.html
        run: dart run replace_maps_api_key_web.dart
      
      - name: Print API_KEY_WEB
        run: echo $API_KEY_WEB

      - name: Build Flutter web
        run: flutter build web --dart-define=API_KEY_WEB=${{ secrets.API_KEY_WEB }}
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          cd build/web
          vercel --prod --token $VERCEL_TOKEN --yes